/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-09-01 18:59:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.VIEWS;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class form_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/S:/sms/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/survey/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1691059203599L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write(" <style>\r\n");
      out.write("        .in\r\n");
      out.write("        {\r\n");
      out.write("            border: 0px;\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin-right: 0.625rem;\r\n");
      out.write("            min-height: 1.25rem;\r\n");
      out.write("            min-width: 1.25rem;\r\n");
      out.write("        }\r\n");
      out.write("        .in_1\r\n");
      out.write("        {\r\n");
      out.write("            height: 40px;\r\n");
      out.write("            border: 0px;\r\n");
      out.write("            border-radius: 2px;\r\n");
      out.write("            display: inline-block;\r\n");
      out.write("            margin-right: 0.625rem;\r\n");
      out.write("            min-height: 1.25rem;\r\n");
      out.write("            min-width: 1.25rem;   \r\n");
      out.write("        }\r\n");
      out.write("    </style>\r\n");
      out.write(" <script>\r\n");
      out.write("      var myhob=0;\r\n");
      out.write("        function changeitt()\r\n");
      out.write("        {\r\n");
      out.write("        	 \r\n");
      out.write("        	\r\n");
      out.write("            createhob.innerHTML = createhob.innerHTML +`<br>`\r\n");
      out.write("            createhob.innerHTML = createhob.innerHTML +`<div class='formcontrol'>`\r\n");
      out.write("            \r\n");
      out.write("        createhob.innerHTML = createhob.innerHTML +`<input type='text' name='a${myhob}' placeholder='Question/Statement' class='in_1' size='60px'><br><br><br>    `\r\n");
      out.write("        createhob.innerHTML = createhob.innerHTML +`<input type='text' name='b${myhob}'\r\n");
      out.write("        placeholder='option 1'  class='in' size='30px'><br><br>`\r\n");
      out.write("        createhob.innerHTML = createhob.innerHTML +`<input type='text' name='c${myhob}' placeholder='option 2'  class='in' size='30px'><br><br>`\r\n");
      out.write("        createhob.innerHTML = createhob.innerHTML +`<input type='text' name='d${myhob}'\r\n");
      out.write("        placeholder='option 3'  class='in' size='30px'><br><br>`\r\n");
      out.write("        createhob.innerHTML = createhob.innerHTML +`<input type='text' name='e${myhob}'\r\n");
      out.write("        placeholder='option 4'  class='in' size='30px'><br><br>`\r\n");
      out.write("\r\n");
      out.write("        createhob.innerHTML = createhob.innerHTML +`</div>`\r\n");
      out.write("        myhob++;\r\n");
      out.write("        		\r\n");
      out.write("       \r\n");
      out.write("		}\r\n");
      out.write("        \r\n");
      out.write("\r\n");
      out.write("    </script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write(" <form action=\"back_1\" method=\"post\">\r\n");
      out.write("     <div class=\"container \">\r\n");
      out.write("        <header class=\"header\">\r\n");
      out.write("            <h1 id=\"title\">\r\n");
      out.write("                Survey for <input type=\"text\" required name=\"txt\" id=\"txt\">\r\n");
      out.write("            </h1>\r\n");
      out.write("            <br>\r\n");
      out.write("            <h2> DESCRIPTION ABOUT YOUR SURVEY</h2>\r\n");
      out.write("            <p id=\"description\">\r\n");
      out.write("               <textarea name = \"txtarea\" rows=\"3\" cols=\"75\" required></textarea>\r\n");
      out.write("            </p>\r\n");
      out.write("        </header>\r\n");
      out.write("       \r\n");
      out.write("\r\n");
      out.write("            <!-- Text section -->\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"name\">Name Of Creator</label>\r\n");
      out.write("                <input type=\"text\" name=\"name\" id=\"name\" class=\"formControl\" placeholder=\"Enter your name\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- end of text section -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Type Email section -->\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"email\">Email</label>\r\n");
      out.write("                <input type=\"email\" name=\"email\" id=\"email\" class=\"formControl\" placeholder=\"Enter your Email\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- end of Email section -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Type Number section -->\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("                <label for=\"phone\">Number of Advices/Questions You want to insert</label>\r\n");
      out.write("                <input type=\"number\" name=\"phone\" id=\"phone\" class=\"formControl\" placeholder=\"Enter your phone number\" required>\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- end of Number section -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Type Number section -->\r\n");
      out.write("            <!-- <div class=\"form-group\">\r\n");
      out.write("                <label for=\"address\">Address <span class=\"clue\">(optional)</span></label>\r\n");
      out.write("                <input type=\"text\" name=\"address\" id=\"address\" class=\"formControl\" placeholder=\"Enter your address\">\r\n");
      out.write("            </div> -->\r\n");
      out.write("            <!--  end of number section -->\r\n");
      out.write("\r\n");
      out.write("            <!-- select section -->\r\n");
      out.write("            <!-- <div class=\"form-group\">\r\n");
      out.write("                <p id=\"quest\">Which option best describe your current role</p>\r\n");
      out.write("                <select name=\"role\" required id=\"dropdown\" class=\"formControl\">\r\n");
      out.write("                    <option value disabled selected >Select current role</option>\r\n");
      out.write("                    <option value=\"student\">Student</option>\r\n");
      out.write("                    <option value=\"student\">Chair Man</option>\r\n");
      out.write("                    <option value=\"teacher\">Teacher</option>\r\n");
      out.write("                    <option value=\"job\">Employee</option>\r\n");
      out.write("                    <option value=\"other\">Other</option>\r\n");
      out.write("                </select>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("            <!-- end of select section -->\r\n");
      out.write("          \r\n");
      out.write("\r\n");
      out.write("           <div class=\"form-group\">\r\n");
      out.write("          \r\n");
      out.write("            <input type=\"button\" value=\"clickHere\" onClick=\"changeitt()\">\r\n");
      out.write("            <div id=\"createhob\"></div>\r\n");
      out.write("\r\n");
      out.write("           </div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- \r\n");
      out.write("            <!-- radio button section -->\r\n");
      out.write("            <!-- <div class=\"form-group\">\r\n");
      out.write("                <p id=\"quest\">How you come to know about WEBHUB ?</p>\r\n");
      out.write("                <label for=\"\">\r\n");
      out.write("                    <input type=\"radio\" name=\"source\" value=\"freinds\"\r\n");
      out.write("                    class=\"inputRadio\"\r\n");
      out.write("                    checked> Friends\r\n");
      out.write("                </label>\r\n");
      out.write("                <label for=\"\">\r\n");
      out.write("                    <input type=\"radio\" name=\"source\" value=\"tv-ads\"\r\n");
      out.write("                    class=\"inputRadio\"\r\n");
      out.write("                    >TV Ads\r\n");
      out.write("                </label>\r\n");
      out.write("                <label for=\"\">\r\n");
      out.write("                    <input type=\"radio\" name=\"source\" value=\"social-media\"\r\n");
      out.write("                    class=\"inputRadio\"\r\n");
      out.write("                    > Social Media\r\n");
      out.write("                </label>\r\n");
      out.write("                <label for=\"\">\r\n");
      out.write("                    <input type=\"radio\" name=\"source\" value=\"newspaper\"\r\n");
      out.write("                    class=\"inputRadio\"\r\n");
      out.write("                    > Newspaper\r\n");
      out.write("                </label>\r\n");
      out.write("                <label for=\"\">\r\n");
      out.write("                    <input type=\"radio\" name=\"source\" value=\"other\"\r\n");
      out.write("                    class=\"inputRadio\"\r\n");
      out.write("                    > Other\r\n");
      out.write("                </label>\r\n");
      out.write("            </div> -->\r\n");
      out.write("            <!-- end of radio button -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Checkbox section -->\r\n");
      out.write("            <!-- <div class=\"form-group\">\r\n");
      out.write("                <p id=\"quest\">Would you like to see improved ? </p>\r\n");
      out.write("                <label for=\"\">\r\n");
      out.write("                    <input type=\"checkbox\" name=\"prefer\" class=\"checkbox\" value=\"front-end-dev\"> Front-end Developer\r\n");
      out.write("                </label>\r\n");
      out.write("                <label for=\"\">\r\n");
      out.write("                    <input type=\"checkbox\" name=\"prefer\" class=\"checkbox\" value=\"back-end-dev\"> Back-end Developer\r\n");
      out.write("                </label>\r\n");
      out.write("                <label for=\"\">\r\n");
      out.write("                    <input type=\"checkbox\" name=\"prefer\" class=\"checkbox\" value=\"app-dev\">  Android App Developer\r\n");
      out.write("                </label>\r\n");
      out.write("                <label for=\"\">\r\n");
      out.write("                    <input type=\"checkbox\" name=\"prefer\" class=\"checkbox\" value=\"soft-engineering\"> Software Engineering\r\n");
      out.write("                </label>\r\n");
      out.write("                <label for=\"\">\r\n");
      out.write("                    <input type=\"checkbox\" name=\"prefer\" class=\"checkbox\" value=\"other\"> Other\r\n");
      out.write("                </label>\r\n");
      out.write("            </div> -->\r\n");
      out.write("            <!-- End of checkbox section -->\r\n");
      out.write("\r\n");
      out.write("            <!-- Textarea section -->\r\n");
      out.write("            <!-- <div class=\"form-group\">\r\n");
      out.write("                <p id=\"quest\">Give us your feedback</p>\r\n");
      out.write("                <textarea name=\"feedback\"  cols=\"30\" rows=\"5\"  id=\"feedback\" class=\"textarea\" placeholder=\"Enter your feedback here...\"></textarea>\r\n");
      out.write("            </div>  -->\r\n");
      out.write("            <div class=\"form-group\">\r\n");
      out.write("              \r\n");
      out.write("                <button type=\"submit\" id=\"submit\" class=\"btn\">Submit</button>\r\n");
      out.write("              \r\n");
      out.write("            </div>\r\n");
      out.write("        \r\n");
      out.write("    </div>\r\n");
      out.write("     </form>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/VIEWS/form.jsp(8,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("resources/css/form.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
