/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.71
 * Generated at: 2023-08-20 17:59:00 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.VIEWS;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class t1_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/S:/ressumebuilder/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/resume_builder/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153365282000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1691059203599L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write(" <script src=\"https://unpkg.com/feather-icons\"></script>\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<link href=\"");
      if (_jspx_meth_c_005furl_005f0(_jspx_page_context))
        return;
      out.write("\" rel=\"stylesheet\">\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("   <div class=\"container\">\r\n");
      out.write("    <div class=\"profile\">\r\n");
      out.write("      <div class=\"profile_container\">\r\n");
      out.write("        \r\n");
      out.write("        <div>\r\n");
      out.write("          <h1 class=\"profile_name\">\r\n");
      out.write("            <span class=\"profile_name_firstName\">");
      out.print(session.getAttribute("name") );
      out.write("</span>\r\n");
      out.write("            <span class=\"profile_name_lastName\">");
      out.print(session.getAttribute("surname") );
      out.write("</span>\r\n");
      out.write("          </h1>\r\n");
      out.write("          <p class=\"profile_title\">");
      out.print(session.getAttribute("desig") );
      out.write("</p>\r\n");
      out.write("          <p class=\"description profile_description\">\r\n");
      out.write("            ");
      out.print(session.getAttribute("dec") );
      out.write("\r\n");
      out.write("          </p>\r\n");
      out.write("          <a class=\"downloadBtn\" href=\"./cv.pdf\" download=\"Resume.pdf\">Download Resume</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"group-1\">\r\n");
      out.write("      <div class=\"skills\">\r\n");
      out.write("        <h3 class=\"title\">Expertise</h3>\r\n");
      out.write("        <ul class=\"skills_list description\">\r\n");
      out.write("          ");
ArrayList<String> q1 = new ArrayList<String>();
      out.write("\r\n");
      out.write("          ");
q1 = (ArrayList<String>)session.getAttribute("s1"); int f = (Integer)session.getAttribute("a");
      out.write("\r\n");
      out.write("          ");
for(int i=0; i<f; i++)
             {
        	   out.println("<html><body><li>"+q1.get(i)+"</li></body></html>");
             }
          
      out.write("\r\n");
      out.write("        </ul>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"ref\">\r\n");
      out.write("        <h3 class=\"title\">Reference</h3>\r\n");
      out.write("        <div class=\"ref_item\">\r\n");
      out.write("          <h4 class=\"ref_name\">Rashid Chy</h4>\r\n");
      out.write("          <p class=\"description\">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Id, neque?</p>\r\n");
      out.write("        </div>\r\n");
      out.write("        <div class=\"ref_item\">\r\n");
      out.write("          <h4 class=\"ref_name\">Ayman Rahman</h4>\r\n");
      out.write("          <p class=\"description\"> Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor\r\n");
      out.write("            incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, </p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"edu\">\r\n");
      out.write("        <h3 class=\"title\">Education</h3>\r\n");
      out.write("        \r\n");
      out.write("         ");
ArrayList<String> q3 = new ArrayList<String>();
      out.write("\r\n");
      out.write("          ");
q3 = (ArrayList<String>)session.getAttribute("s3"); int f3 = (Integer)session.getAttribute("c"); int x=0;
      out.write("\r\n");
      out.write("          ");
for(int i=0; i<f3; i++)
             {
        	   out.println("<html><body><div class='edu_item'> <p class='item_preTitle'>"+q3.get(x)+"</p></div></body></html>");
        	   x++;
        	   out.println("<html><body><div class='edu_item'> <h4 class='item_title'>"+q3.get(x)+"</h4></div></body></html>");
        	   x++;
        	   out.println("<html><body><div class='edu_item'> <p class='item_subtitle'>"+q3.get(x)+"</p></div></body></html>");
        	   x++;	
        	   out.println("<html><body><br></body></html>");
             }
          
      out.write("\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"certification\">\r\n");
      out.write("        <h3 class=\"title\">certification</h3>\r\n");
      out.write("        <div class=\"certification_item\">\r\n");
      out.write("           ");
ArrayList<String> q4 = new ArrayList<String>();
      out.write("\r\n");
      out.write("          ");
q4 = (ArrayList<String>)session.getAttribute("s5"); int f4 = (Integer)session.getAttribute("e"); int x1=0;
      out.write("\r\n");
      out.write("          ");
for(int i=0; i<f4; i++)
             {
        	   out.println("<html><body><div class='edu_item'> <p class='item_preTitle'>"+q4.get(x1)+"</p></div></body></html>");
        	   x1++;
        	   out.println("<html><body><div class='edu_item'> <h4 class='item_title'>"+q4.get(x1)+"</h4></div></body></html>");
        	   x1++;
        	   out.println("<html><body><br></body></html>");
             }
          
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    <div class=\"group-2\">\r\n");
      out.write("      <div class=\"exp\">\r\n");
      out.write("        <h3 class=\"title\">Experience</h3>\r\n");
      out.write("       \r\n");
      out.write("         ");
ArrayList<String> q5 = new ArrayList<String>();
      out.write("\r\n");
      out.write("          ");
q5 = (ArrayList<String>)session.getAttribute("s4"); int f5 = (Integer)session.getAttribute("d"); int x2=0;
      out.write("\r\n");
      out.write("          ");
for(int i=0; i<f5; i++)
             {
        	   out.println("<html><body><div class='exp_item'> <p class='item_preTitle'>"+q5.get(x2)+"</p></div></body></html>");
        	   x2++;
        	   out.println("<html><body><div class='exp_item'> <h4 class='item_title'>"+q5.get(x2)+"</h4></div></body></html>");
        	   x2++;
        	   out.println("<html><body><div class='exp_item'> <p class='item_subtitle'>"+q5.get(x2)+"</p></div></body></html>");
        	   x2++;
        	   out.println("<html><body><br></body></html>");
             }
          
      out.write("\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"awards\">\r\n");
      out.write("        <h3 class=\"title\">Awards</h3>\r\n");
      out.write("        <div class=\"awards_item\">\r\n");
      out.write("          \r\n");
      out.write("          ");
ArrayList<String> q6 = new ArrayList<String>();
      out.write("\r\n");
      out.write("          ");
q6 = (ArrayList<String>)session.getAttribute("s6"); int f6 = (Integer)session.getAttribute("h"); int x3=0;
      out.write("\r\n");
      out.write("          ");
for(int i=0; i<f6; i++)
             {
        	   out.println("<html><body><div class='awards_item'><p class='item_preTitle'>"+q6.get(x3)+"</p></div></body></html>");
        	   x3++;
        	   out.println("<html><body><div class='awards_item'><h4 class='item_title'>"+q6.get(x3)+"</h4></div></body></html>");
        	   x3++;
        	   out.println("<html><body><div class='awards_item'><p class='description'>"+q6.get(x3)+"</p></div></body></html>");
        	   x3++;
        	   out.println("<html><body><br></body></html>");
             }
          
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("      </div>\r\n");
      out.write("\r\n");
      out.write("      <div class=\"interest\">\r\n");
      out.write("        <h3 class=\"title\">Interest</h3>\r\n");
      out.write("        <div class=\"interest_items\">\r\n");
      out.write("            ");
ArrayList<String> q2 = new ArrayList<String>();
      out.write("\r\n");
      out.write("          ");
q2 = (ArrayList<String>)session.getAttribute("s2"); int f1 = (Integer)session.getAttribute("f");
      out.write("\r\n");
      out.write("          ");
for(int i=0; i<f1; i++)
             {
        	   out.println("<html><body><div class='interest_item'><span>"+q2.get(i)+"</span></div></body></html>");
             }
          
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    <hr>\r\n");
      out.write("    <div class=\"group-3\">\r\n");
      out.write("      <div class=\"contact\">\r\n");
      out.write("        <h3 class=\"title\">Contact</h3>\r\n");
      out.write("        <div class=\"contact_info\">\r\n");
      out.write("          <p class=\"description\">\r\n");
      out.write("            ");
      out.print(session.getAttribute("state"));
      out.write(',');
      out.print(session.getAttribute("city"));
      out.write("\r\n");
      out.write("          </p>\r\n");
      out.write("          <p class=\"description\">\r\n");
      out.write("            ");
      out.print(session.getAttribute("num") );
      out.write("\r\n");
      out.write("          </p>\r\n");
      out.write("          <p class=\"description\">\r\n");
      out.write("            ");
      out.print(session.getAttribute("mail") );
      out.write("\r\n");
      out.write("          </p>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"social\">\r\n");
      out.write("        <h3 class=\"title\">Socials</h3>\r\n");
      out.write("        <div class=\"social_items\">\r\n");
      out.write("          <a href=\"#\" target=\"_b\" class=\"social_item\">\r\n");
      out.write("            <i data-feather=\"github\"></i>\r\n");
      out.write("            <span>");
      out.print(session.getAttribute("ur1"));
      out.write("</span>\r\n");
      out.write("          </a>\r\n");
      out.write("          <a href=\"#\" target=\"_blank\" class=\"social_item\">\r\n");
      out.write("            <i data-feather=\"twitter\"></i>\r\n");
      out.write("            <span>");
      out.print(session.getAttribute("ur2") );
      out.write("</span>\r\n");
      out.write("          </a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("  <script>\r\n");
      out.write("    feather.replace()\r\n");
      out.write("  </script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005furl_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:url
    org.apache.taglibs.standard.tag.rt.core.UrlTag _jspx_th_c_005furl_005f0 = (org.apache.taglibs.standard.tag.rt.core.UrlTag) _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.UrlTag.class);
    boolean _jspx_th_c_005furl_005f0_reused = false;
    try {
      _jspx_th_c_005furl_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005furl_005f0.setParent(null);
      // /WEB-INF/VIEWS/t1.jsp(11,12) name = value type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005furl_005f0.setValue("resources/css/t1.css");
      int _jspx_eval_c_005furl_005f0 = _jspx_th_c_005furl_005f0.doStartTag();
      if (_jspx_th_c_005furl_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005furl_0026_005fvalue_005fnobody.reuse(_jspx_th_c_005furl_005f0);
      _jspx_th_c_005furl_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005furl_005f0, _jsp_getInstanceManager(), _jspx_th_c_005furl_005f0_reused);
    }
    return false;
  }
}
